# Generated by Django 4.2 on 2023-04-28 16:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('name', models.CharField(default=None, max_length=56)),
                ('description', models.CharField(default=' Good quality product', max_length=500)),
                ('image', models.ImageField(upload_to=app.models.upload_path)),
                ('price', models.IntegerField()),
                ('offer_price', models.IntegerField()),
                ('category', models.CharField(choices=[('Birthday', 'hbd'), ('Anniversary', 'anv'), ('Valentine', 'vlt'), ('Flowers', 'flw'), ('Chocolate', 'clt'), ('Plants', 'pla'), ('Electronic', 'elt'), ('Jewels', 'jwl')], max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
