# Generated by Django 4.1.7 on 2023-04-30 11:43

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('name', models.CharField(default=None, max_length=56)),
                ('description', models.CharField(default=' Good quality product', max_length=500)),
                ('image', models.ImageField(upload_to=app.models.upload_path)),
                ('price', models.IntegerField()),
                ('offer_price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Birthday', 'hbd'), ('Electronic', 'elt'), ('Anniversary', 'anv'), ('Flowers', 'flw'), ('Chocolate', 'clt'), ('Jewels', 'jwl')], max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
