# Generated by Django 4.1.7 on 2023-04-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='offer_price',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Birthday', 'hbd'), ('Anniversary', 'anv'), ('Valentine', 'vlt'), ('Flowers', 'flw'), ('Chocolate', 'clt'), ('Electronic', 'elt'), ('Jewels', 'jwl')], max_length=20),
        ),
    ]
