# Generated by Django 4.1.7 on 2023-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wishlist_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=500),
        ),
    ]
