# Generated by Django 4.2 on 2023-05-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wishlist_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='ip',
        ),
    ]
