# Generated by Django 4.1.7 on 2023-04-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Birthday', 'hbd'), ('Electronic', 'elt'), ('Anniversary', 'anv'), ('Valentine', 'vlt'), ('Flowers', 'flw'), ('Chocolate', 'clt'), ('Jewels', 'jwl')], max_length=20),
        ),
    ]
