# Generated by Django 4.2 on 2023-05-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_additonal_address_customer_additional_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
