# Generated by Django 4.1.7 on 2023-05-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_searchresult_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ip',
            field=models.TextField(default='0.0.0.0'),
        ),
    ]
