# Generated by Django 4.1.7 on 2023-05-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'delivered'), ('Accepted', 'arriving'), ('Pending', 'pending')], default='pending', max_length=10),
        ),
    ]
