# Generated by Django 4.1.7 on 2023-05-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_order_status_forget_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='pending', max_length=10),
        ),
    ]
